// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_INCLUDED_msg_2eproto
#define PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
namespace config {
class EbcMsg;
class EbcMsgDefaultTypeInternal;
extern EbcMsgDefaultTypeInternal _EbcMsg_default_instance_;
class EbcNode;
class EbcNodeDefaultTypeInternal;
extern EbcNodeDefaultTypeInternal _EbcNode_default_instance_;
class EbcNodes;
class EbcNodesDefaultTypeInternal;
extern EbcNodesDefaultTypeInternal _EbcNodes_default_instance_;
class search;
class searchDefaultTypeInternal;
extern searchDefaultTypeInternal _search_default_instance_;
}  // namespace config
namespace google {
namespace protobuf {
template<> ::config::EbcMsg* Arena::CreateMaybeMessage<::config::EbcMsg>(Arena*);
template<> ::config::EbcNode* Arena::CreateMaybeMessage<::config::EbcNode>(Arena*);
template<> ::config::EbcNodes* Arena::CreateMaybeMessage<::config::EbcNodes>(Arena*);
template<> ::config::search* Arena::CreateMaybeMessage<::config::search>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace config {

enum MsgType {
  EMPTY = 0,
  GET_NODE = 1,
  GET_DATA = 2,
  PING = 3,
  HEART = 4,
  REP = 5,
  PUNCH = 6,
  MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool MsgType_IsValid(int value);
const MsgType MsgType_MIN = EMPTY;
const MsgType MsgType_MAX = PUNCH;
const int MsgType_ARRAYSIZE = MsgType_MAX + 1;

enum MsgSubType {
  EMPTY_SUB = 0,
  PONG = 1,
  NODE = 2,
  DATA = 3,
  MsgSubType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  MsgSubType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool MsgSubType_IsValid(int value);
const MsgSubType MsgSubType_MIN = EMPTY_SUB;
const MsgSubType MsgSubType_MAX = DATA;
const int MsgSubType_ARRAYSIZE = MsgSubType_MAX + 1;

// ===================================================================

class EbcNode final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:config.EbcNode) */ {
 public:
  EbcNode();
  virtual ~EbcNode();

  EbcNode(const EbcNode& from);

  inline EbcNode& operator=(const EbcNode& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EbcNode(EbcNode&& from) noexcept
    : EbcNode() {
    *this = ::std::move(from);
  }

  inline EbcNode& operator=(EbcNode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const EbcNode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EbcNode* internal_default_instance() {
    return reinterpret_cast<const EbcNode*>(
               &_EbcNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(EbcNode* other);
  friend void swap(EbcNode& a, EbcNode& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EbcNode* New() const final {
    return CreateMaybeMessage<EbcNode>(nullptr);
  }

  EbcNode* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EbcNode>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const EbcNode& from);
  void MergeFrom(const EbcNode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EbcNode* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const void* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // uint32 ip = 2;
  void clear_ip();
  static const int kIpFieldNumber = 2;
  ::google::protobuf::uint32 ip() const;
  void set_ip(::google::protobuf::uint32 value);

  // uint32 port_nat = 3;
  void clear_port_nat();
  static const int kPortNatFieldNumber = 3;
  ::google::protobuf::uint32 port_nat() const;
  void set_port_nat(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:config.EbcNode)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::uint32 ip_;
  ::google::protobuf::uint32 port_nat_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class EbcNodes final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:config.EbcNodes) */ {
 public:
  EbcNodes();
  virtual ~EbcNodes();

  EbcNodes(const EbcNodes& from);

  inline EbcNodes& operator=(const EbcNodes& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EbcNodes(EbcNodes&& from) noexcept
    : EbcNodes() {
    *this = ::std::move(from);
  }

  inline EbcNodes& operator=(EbcNodes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const EbcNodes& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EbcNodes* internal_default_instance() {
    return reinterpret_cast<const EbcNodes*>(
               &_EbcNodes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(EbcNodes* other);
  friend void swap(EbcNodes& a, EbcNodes& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EbcNodes* New() const final {
    return CreateMaybeMessage<EbcNodes>(nullptr);
  }

  EbcNodes* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EbcNodes>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const EbcNodes& from);
  void MergeFrom(const EbcNodes& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EbcNodes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .config.EbcNode ebcNodes = 1;
  int ebcnodes_size() const;
  void clear_ebcnodes();
  static const int kEbcNodesFieldNumber = 1;
  ::config::EbcNode* mutable_ebcnodes(int index);
  ::google::protobuf::RepeatedPtrField< ::config::EbcNode >*
      mutable_ebcnodes();
  const ::config::EbcNode& ebcnodes(int index) const;
  ::config::EbcNode* add_ebcnodes();
  const ::google::protobuf::RepeatedPtrField< ::config::EbcNode >&
      ebcnodes() const;

  // @@protoc_insertion_point(class_scope:config.EbcNodes)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::config::EbcNode > ebcnodes_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class search final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:config.search) */ {
 public:
  search();
  virtual ~search();

  search(const search& from);

  inline search& operator=(const search& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  search(search&& from) noexcept
    : search() {
    *this = ::std::move(from);
  }

  inline search& operator=(search&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const search& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const search* internal_default_instance() {
    return reinterpret_cast<const search*>(
               &_search_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(search* other);
  friend void swap(search& a, search& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline search* New() const final {
    return CreateMaybeMessage<search>(nullptr);
  }

  search* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<search>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const search& from);
  void MergeFrom(const search& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(search* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes tid = 2;
  void clear_tid();
  static const int kTidFieldNumber = 2;
  const ::std::string& tid() const;
  void set_tid(const ::std::string& value);
  #if LANG_CXX11
  void set_tid(::std::string&& value);
  #endif
  void set_tid(const char* value);
  void set_tid(const void* value, size_t size);
  ::std::string* mutable_tid();
  ::std::string* release_tid();
  void set_allocated_tid(::std::string* tid);

  // bytes targetId = 3;
  void clear_targetid();
  static const int kTargetIdFieldNumber = 3;
  const ::std::string& targetid() const;
  void set_targetid(const ::std::string& value);
  #if LANG_CXX11
  void set_targetid(::std::string&& value);
  #endif
  void set_targetid(const char* value);
  void set_targetid(const void* value, size_t size);
  ::std::string* mutable_targetid();
  ::std::string* release_targetid();
  void set_allocated_targetid(::std::string* targetid);

  // bytes value = 5;
  void clear_value();
  static const int kValueFieldNumber = 5;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // .config.EbcNodes nodes = 4;
  bool has_nodes() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 4;
  const ::config::EbcNodes& nodes() const;
  ::config::EbcNodes* release_nodes();
  ::config::EbcNodes* mutable_nodes();
  void set_allocated_nodes(::config::EbcNodes* nodes);

  // bool isId = 1;
  void clear_isid();
  static const int kIsIdFieldNumber = 1;
  bool isid() const;
  void set_isid(bool value);

  // @@protoc_insertion_point(class_scope:config.search)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr tid_;
  ::google::protobuf::internal::ArenaStringPtr targetid_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::config::EbcNodes* nodes_;
  bool isid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class EbcMsg final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:config.EbcMsg) */ {
 public:
  EbcMsg();
  virtual ~EbcMsg();

  EbcMsg(const EbcMsg& from);

  inline EbcMsg& operator=(const EbcMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EbcMsg(EbcMsg&& from) noexcept
    : EbcMsg() {
    *this = ::std::move(from);
  }

  inline EbcMsg& operator=(EbcMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const EbcMsg& default_instance();

  enum BodyCase {
    kMsg = 10,
    kNodes = 11,
    BODY_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EbcMsg* internal_default_instance() {
    return reinterpret_cast<const EbcMsg*>(
               &_EbcMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(EbcMsg* other);
  friend void swap(EbcMsg& a, EbcMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EbcMsg* New() const final {
    return CreateMaybeMessage<EbcMsg>(nullptr);
  }

  EbcMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EbcMsg>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const EbcMsg& from);
  void MergeFrom(const EbcMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EbcMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string version = 2;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  #if LANG_CXX11
  void set_version(::std::string&& value);
  #endif
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // bytes src_id = 3;
  void clear_src_id();
  static const int kSrcIdFieldNumber = 3;
  const ::std::string& src_id() const;
  void set_src_id(const ::std::string& value);
  #if LANG_CXX11
  void set_src_id(::std::string&& value);
  #endif
  void set_src_id(const char* value);
  void set_src_id(const void* value, size_t size);
  ::std::string* mutable_src_id();
  ::std::string* release_src_id();
  void set_allocated_src_id(::std::string* src_id);

  // uint32 head = 1;
  void clear_head();
  static const int kHeadFieldNumber = 1;
  ::google::protobuf::uint32 head() const;
  void set_head(::google::protobuf::uint32 value);

  // uint32 ttl = 5;
  void clear_ttl();
  static const int kTtlFieldNumber = 5;
  ::google::protobuf::uint32 ttl() const;
  void set_ttl(::google::protobuf::uint32 value);

  // uint32 id = 6;
  void clear_id();
  static const int kIdFieldNumber = 6;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // .config.MsgType type = 7;
  void clear_type();
  static const int kTypeFieldNumber = 7;
  ::config::MsgType type() const;
  void set_type(::config::MsgType value);

  // .config.MsgSubType sub_type = 8;
  void clear_sub_type();
  static const int kSubTypeFieldNumber = 8;
  ::config::MsgSubType sub_type() const;
  void set_sub_type(::config::MsgSubType value);

  // uint32 length = 9;
  void clear_length();
  static const int kLengthFieldNumber = 9;
  ::google::protobuf::uint32 length() const;
  void set_length(::google::protobuf::uint32 value);

  // .config.search msg = 10;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 10;
  const ::config::search& msg() const;
  ::config::search* release_msg();
  ::config::search* mutable_msg();
  void set_allocated_msg(::config::search* msg);

  // .config.EbcNodes nodes = 11;
  bool has_nodes() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 11;
  const ::config::EbcNodes& nodes() const;
  ::config::EbcNodes* release_nodes();
  ::config::EbcNodes* mutable_nodes();
  void set_allocated_nodes(::config::EbcNodes* nodes);

  void clear_body();
  BodyCase body_case() const;
  // @@protoc_insertion_point(class_scope:config.EbcMsg)
 private:
  class HasBitSetters;
  void set_has_msg();
  void set_has_nodes();

  inline bool has_body() const;
  inline void clear_has_body();

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr src_id_;
  ::google::protobuf::uint32 head_;
  ::google::protobuf::uint32 ttl_;
  ::google::protobuf::uint32 id_;
  int type_;
  int sub_type_;
  ::google::protobuf::uint32 length_;
  union BodyUnion {
    BodyUnion() {}
    ::config::search* msg_;
    ::config::EbcNodes* nodes_;
  } body_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EbcNode

// bytes id = 1;
inline void EbcNode::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& EbcNode::id() const {
  // @@protoc_insertion_point(field_get:config.EbcNode.id)
  return id_.GetNoArena();
}
inline void EbcNode::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:config.EbcNode.id)
}
#if LANG_CXX11
inline void EbcNode::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:config.EbcNode.id)
}
#endif
inline void EbcNode::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:config.EbcNode.id)
}
inline void EbcNode::set_id(const void* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:config.EbcNode.id)
}
inline ::std::string* EbcNode::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:config.EbcNode.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* EbcNode::release_id() {
  // @@protoc_insertion_point(field_release:config.EbcNode.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void EbcNode::set_allocated_id(::std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:config.EbcNode.id)
}

// uint32 ip = 2;
inline void EbcNode::clear_ip() {
  ip_ = 0u;
}
inline ::google::protobuf::uint32 EbcNode::ip() const {
  // @@protoc_insertion_point(field_get:config.EbcNode.ip)
  return ip_;
}
inline void EbcNode::set_ip(::google::protobuf::uint32 value) {
  
  ip_ = value;
  // @@protoc_insertion_point(field_set:config.EbcNode.ip)
}

// uint32 port_nat = 3;
inline void EbcNode::clear_port_nat() {
  port_nat_ = 0u;
}
inline ::google::protobuf::uint32 EbcNode::port_nat() const {
  // @@protoc_insertion_point(field_get:config.EbcNode.port_nat)
  return port_nat_;
}
inline void EbcNode::set_port_nat(::google::protobuf::uint32 value) {
  
  port_nat_ = value;
  // @@protoc_insertion_point(field_set:config.EbcNode.port_nat)
}

// -------------------------------------------------------------------

// EbcNodes

// repeated .config.EbcNode ebcNodes = 1;
inline int EbcNodes::ebcnodes_size() const {
  return ebcnodes_.size();
}
inline void EbcNodes::clear_ebcnodes() {
  ebcnodes_.Clear();
}
inline ::config::EbcNode* EbcNodes::mutable_ebcnodes(int index) {
  // @@protoc_insertion_point(field_mutable:config.EbcNodes.ebcNodes)
  return ebcnodes_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::config::EbcNode >*
EbcNodes::mutable_ebcnodes() {
  // @@protoc_insertion_point(field_mutable_list:config.EbcNodes.ebcNodes)
  return &ebcnodes_;
}
inline const ::config::EbcNode& EbcNodes::ebcnodes(int index) const {
  // @@protoc_insertion_point(field_get:config.EbcNodes.ebcNodes)
  return ebcnodes_.Get(index);
}
inline ::config::EbcNode* EbcNodes::add_ebcnodes() {
  // @@protoc_insertion_point(field_add:config.EbcNodes.ebcNodes)
  return ebcnodes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::config::EbcNode >&
EbcNodes::ebcnodes() const {
  // @@protoc_insertion_point(field_list:config.EbcNodes.ebcNodes)
  return ebcnodes_;
}

// -------------------------------------------------------------------

// search

// bool isId = 1;
inline void search::clear_isid() {
  isid_ = false;
}
inline bool search::isid() const {
  // @@protoc_insertion_point(field_get:config.search.isId)
  return isid_;
}
inline void search::set_isid(bool value) {
  
  isid_ = value;
  // @@protoc_insertion_point(field_set:config.search.isId)
}

// bytes tid = 2;
inline void search::clear_tid() {
  tid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& search::tid() const {
  // @@protoc_insertion_point(field_get:config.search.tid)
  return tid_.GetNoArena();
}
inline void search::set_tid(const ::std::string& value) {
  
  tid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:config.search.tid)
}
#if LANG_CXX11
inline void search::set_tid(::std::string&& value) {
  
  tid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:config.search.tid)
}
#endif
inline void search::set_tid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:config.search.tid)
}
inline void search::set_tid(const void* value, size_t size) {
  
  tid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:config.search.tid)
}
inline ::std::string* search::mutable_tid() {
  
  // @@protoc_insertion_point(field_mutable:config.search.tid)
  return tid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* search::release_tid() {
  // @@protoc_insertion_point(field_release:config.search.tid)
  
  return tid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void search::set_allocated_tid(::std::string* tid) {
  if (tid != nullptr) {
    
  } else {
    
  }
  tid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tid);
  // @@protoc_insertion_point(field_set_allocated:config.search.tid)
}

// bytes targetId = 3;
inline void search::clear_targetid() {
  targetid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& search::targetid() const {
  // @@protoc_insertion_point(field_get:config.search.targetId)
  return targetid_.GetNoArena();
}
inline void search::set_targetid(const ::std::string& value) {
  
  targetid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:config.search.targetId)
}
#if LANG_CXX11
inline void search::set_targetid(::std::string&& value) {
  
  targetid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:config.search.targetId)
}
#endif
inline void search::set_targetid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  targetid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:config.search.targetId)
}
inline void search::set_targetid(const void* value, size_t size) {
  
  targetid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:config.search.targetId)
}
inline ::std::string* search::mutable_targetid() {
  
  // @@protoc_insertion_point(field_mutable:config.search.targetId)
  return targetid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* search::release_targetid() {
  // @@protoc_insertion_point(field_release:config.search.targetId)
  
  return targetid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void search::set_allocated_targetid(::std::string* targetid) {
  if (targetid != nullptr) {
    
  } else {
    
  }
  targetid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), targetid);
  // @@protoc_insertion_point(field_set_allocated:config.search.targetId)
}

// .config.EbcNodes nodes = 4;
inline bool search::has_nodes() const {
  return this != internal_default_instance() && nodes_ != nullptr;
}
inline void search::clear_nodes() {
  if (GetArenaNoVirtual() == nullptr && nodes_ != nullptr) {
    delete nodes_;
  }
  nodes_ = nullptr;
}
inline const ::config::EbcNodes& search::nodes() const {
  const ::config::EbcNodes* p = nodes_;
  // @@protoc_insertion_point(field_get:config.search.nodes)
  return p != nullptr ? *p : *reinterpret_cast<const ::config::EbcNodes*>(
      &::config::_EbcNodes_default_instance_);
}
inline ::config::EbcNodes* search::release_nodes() {
  // @@protoc_insertion_point(field_release:config.search.nodes)
  
  ::config::EbcNodes* temp = nodes_;
  nodes_ = nullptr;
  return temp;
}
inline ::config::EbcNodes* search::mutable_nodes() {
  
  if (nodes_ == nullptr) {
    auto* p = CreateMaybeMessage<::config::EbcNodes>(GetArenaNoVirtual());
    nodes_ = p;
  }
  // @@protoc_insertion_point(field_mutable:config.search.nodes)
  return nodes_;
}
inline void search::set_allocated_nodes(::config::EbcNodes* nodes) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete nodes_;
  }
  if (nodes) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      nodes = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, nodes, submessage_arena);
    }
    
  } else {
    
  }
  nodes_ = nodes;
  // @@protoc_insertion_point(field_set_allocated:config.search.nodes)
}

// bytes value = 5;
inline void search::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& search::value() const {
  // @@protoc_insertion_point(field_get:config.search.value)
  return value_.GetNoArena();
}
inline void search::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:config.search.value)
}
#if LANG_CXX11
inline void search::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:config.search.value)
}
#endif
inline void search::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:config.search.value)
}
inline void search::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:config.search.value)
}
inline ::std::string* search::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:config.search.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* search::release_value() {
  // @@protoc_insertion_point(field_release:config.search.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void search::set_allocated_value(::std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:config.search.value)
}

// -------------------------------------------------------------------

// EbcMsg

// uint32 head = 1;
inline void EbcMsg::clear_head() {
  head_ = 0u;
}
inline ::google::protobuf::uint32 EbcMsg::head() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.head)
  return head_;
}
inline void EbcMsg::set_head(::google::protobuf::uint32 value) {
  
  head_ = value;
  // @@protoc_insertion_point(field_set:config.EbcMsg.head)
}

// string version = 2;
inline void EbcMsg::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& EbcMsg::version() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.version)
  return version_.GetNoArena();
}
inline void EbcMsg::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:config.EbcMsg.version)
}
#if LANG_CXX11
inline void EbcMsg::set_version(::std::string&& value) {
  
  version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:config.EbcMsg.version)
}
#endif
inline void EbcMsg::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:config.EbcMsg.version)
}
inline void EbcMsg::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:config.EbcMsg.version)
}
inline ::std::string* EbcMsg::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:config.EbcMsg.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* EbcMsg::release_version() {
  // @@protoc_insertion_point(field_release:config.EbcMsg.version)
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void EbcMsg::set_allocated_version(::std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:config.EbcMsg.version)
}

// bytes src_id = 3;
inline void EbcMsg::clear_src_id() {
  src_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& EbcMsg::src_id() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.src_id)
  return src_id_.GetNoArena();
}
inline void EbcMsg::set_src_id(const ::std::string& value) {
  
  src_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:config.EbcMsg.src_id)
}
#if LANG_CXX11
inline void EbcMsg::set_src_id(::std::string&& value) {
  
  src_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:config.EbcMsg.src_id)
}
#endif
inline void EbcMsg::set_src_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  src_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:config.EbcMsg.src_id)
}
inline void EbcMsg::set_src_id(const void* value, size_t size) {
  
  src_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:config.EbcMsg.src_id)
}
inline ::std::string* EbcMsg::mutable_src_id() {
  
  // @@protoc_insertion_point(field_mutable:config.EbcMsg.src_id)
  return src_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* EbcMsg::release_src_id() {
  // @@protoc_insertion_point(field_release:config.EbcMsg.src_id)
  
  return src_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void EbcMsg::set_allocated_src_id(::std::string* src_id) {
  if (src_id != nullptr) {
    
  } else {
    
  }
  src_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), src_id);
  // @@protoc_insertion_point(field_set_allocated:config.EbcMsg.src_id)
}

// uint32 ttl = 5;
inline void EbcMsg::clear_ttl() {
  ttl_ = 0u;
}
inline ::google::protobuf::uint32 EbcMsg::ttl() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.ttl)
  return ttl_;
}
inline void EbcMsg::set_ttl(::google::protobuf::uint32 value) {
  
  ttl_ = value;
  // @@protoc_insertion_point(field_set:config.EbcMsg.ttl)
}

// uint32 id = 6;
inline void EbcMsg::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 EbcMsg::id() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.id)
  return id_;
}
inline void EbcMsg::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:config.EbcMsg.id)
}

// .config.MsgType type = 7;
inline void EbcMsg::clear_type() {
  type_ = 0;
}
inline ::config::MsgType EbcMsg::type() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.type)
  return static_cast< ::config::MsgType >(type_);
}
inline void EbcMsg::set_type(::config::MsgType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:config.EbcMsg.type)
}

// .config.MsgSubType sub_type = 8;
inline void EbcMsg::clear_sub_type() {
  sub_type_ = 0;
}
inline ::config::MsgSubType EbcMsg::sub_type() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.sub_type)
  return static_cast< ::config::MsgSubType >(sub_type_);
}
inline void EbcMsg::set_sub_type(::config::MsgSubType value) {
  
  sub_type_ = value;
  // @@protoc_insertion_point(field_set:config.EbcMsg.sub_type)
}

// uint32 length = 9;
inline void EbcMsg::clear_length() {
  length_ = 0u;
}
inline ::google::protobuf::uint32 EbcMsg::length() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.length)
  return length_;
}
inline void EbcMsg::set_length(::google::protobuf::uint32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:config.EbcMsg.length)
}

// .config.search msg = 10;
inline bool EbcMsg::has_msg() const {
  return body_case() == kMsg;
}
inline void EbcMsg::set_has_msg() {
  _oneof_case_[0] = kMsg;
}
inline void EbcMsg::clear_msg() {
  if (has_msg()) {
    delete body_.msg_;
    clear_has_body();
  }
}
inline ::config::search* EbcMsg::release_msg() {
  // @@protoc_insertion_point(field_release:config.EbcMsg.msg)
  if (has_msg()) {
    clear_has_body();
      ::config::search* temp = body_.msg_;
    body_.msg_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::config::search& EbcMsg::msg() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.msg)
  return has_msg()
      ? *body_.msg_
      : *reinterpret_cast< ::config::search*>(&::config::_search_default_instance_);
}
inline ::config::search* EbcMsg::mutable_msg() {
  if (!has_msg()) {
    clear_body();
    set_has_msg();
    body_.msg_ = CreateMaybeMessage< ::config::search >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:config.EbcMsg.msg)
  return body_.msg_;
}

// .config.EbcNodes nodes = 11;
inline bool EbcMsg::has_nodes() const {
  return body_case() == kNodes;
}
inline void EbcMsg::set_has_nodes() {
  _oneof_case_[0] = kNodes;
}
inline void EbcMsg::clear_nodes() {
  if (has_nodes()) {
    delete body_.nodes_;
    clear_has_body();
  }
}
inline ::config::EbcNodes* EbcMsg::release_nodes() {
  // @@protoc_insertion_point(field_release:config.EbcMsg.nodes)
  if (has_nodes()) {
    clear_has_body();
      ::config::EbcNodes* temp = body_.nodes_;
    body_.nodes_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::config::EbcNodes& EbcMsg::nodes() const {
  // @@protoc_insertion_point(field_get:config.EbcMsg.nodes)
  return has_nodes()
      ? *body_.nodes_
      : *reinterpret_cast< ::config::EbcNodes*>(&::config::_EbcNodes_default_instance_);
}
inline ::config::EbcNodes* EbcMsg::mutable_nodes() {
  if (!has_nodes()) {
    clear_body();
    set_has_nodes();
    body_.nodes_ = CreateMaybeMessage< ::config::EbcNodes >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:config.EbcMsg.nodes)
  return body_.nodes_;
}

inline bool EbcMsg::has_body() const {
  return body_case() != BODY_NOT_SET;
}
inline void EbcMsg::clear_has_body() {
  _oneof_case_[0] = BODY_NOT_SET;
}
inline EbcMsg::BodyCase EbcMsg::body_case() const {
  return EbcMsg::BodyCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace config

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::config::MsgType> : ::std::true_type {};
template <> struct is_proto_enum< ::config::MsgSubType> : ::std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_msg_2eproto
